name: tbot
channels:
  - defaults
  - conda-forge
  - Microsoft
dependencies:
  - python=3.11
  - pip
  - setuptools
  - wheel
  - pip:
    - requests
    - python-dotenv
    - pydantic
    - aiohttp
    - aiofiles
    - colorama
    - cachetools
    - solana