name: GitHub Actions Version Updater

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.2
        with:
          # [Required] Access token with `workflow` scope.
          token: ${{ secrets.PAT }}

      - name: Run GitHub Actions Version Updater
        uses: saadmk11/github-actions-version-updater@v0.8.1
        with:
          # [Required] Access token with `workflow` scope.
          token: ${{ secrets.PAT }}
          pull_request_title: "ci: Update GitHub Actions to Latest Version"